Repository brandondombrowsky/BastCastle, pull requests merged in 2023-02, with the labels that each got.

#75 Add gitignore
  .gitignore
  home-assistant/configuration.yaml
  home-assistant/example_secrets.yaml
Labels: priority-high

#94 deleted hello-world folder
  hello-world/.gitignore
  hello-world/README.md
  hello-world/package-lock.json
  hello-world/package.json
  hello-world/public/favicon.ico
  hello-world/public/index.html
  hello-world/public/logo192.png
  hello-world/public/logo512.png
  hello-world/public/manifest.json
  hello-world/public/robots.txt
  hello-world/src/App.css
  hello-world/src/App.js
  hello-world/src/App.test.js
  hello-world/src/index.css
  hello-world/src/index.js
  hello-world/src/logo.svg
  hello-world/src/reportWebVitals.js
  hello-world/src/setupTests.js
  package-lock.json
Labels: week6

#101 Add CI for HomeAssistant configuration files
  .github/workflows/home-assistant.yml
  automations.yaml
  configuration.yaml
  example_secrets.yaml
  scenes.yaml
  scripts.yaml
  scripts/loop_6_times.yaml
  scripts/scripts.yaml
Labels: week6

#127 Add a yaml linter file to scripts
  .github/workflows/yamllint.yml
  automations.yaml
  configuration.yaml
  example_secrets.yaml
  scenes.yaml
  scripts.yaml
  scripts/loop_6_times.yaml
  scripts/scripts.yaml
Labels: week7, priority-high

#151 Move HA files to separate folder
  .github/workflows/home-assistant.yml
  homeassistant-config/automations.yaml
  homeassistant-config/configuration.yaml
  homeassistant-config/example_secrets.yaml
  homeassistant-config/scenes.yaml
  homeassistant-config/scripts.yaml
  homeassistant-config/scripts/loop_6_times.yaml
  homeassistant-config/scripts/scripts.yaml
Labels: week8, priority-medium

#154 Udate ReadMe - Silly and Fun
  README.md
Labels: week7, week8, week9, priority-low

#153 Add test CD file
  .github/workflows/deployment.yml
  .github/workflows/yamllint.yml
Labels: week8, priority-low

#156 CD - deploy to EC2 instance
  .github/workflows/deployment.yml
Labels: week8, priority-medium

#157 Change local HA config directory
  .github/workflows/deployment.yml
Labels: week8, priority-medium

#160 Make local path the same as Kyle's
  .github/workflows/deployment.yml
Labels: priority-medium

#164 Second pass at ReadMe.
  README.md
Labels: priority-low

#166 Deploy configuration files to EC2 instance
  .github/workflows/deployment.yml
Labels: week8, priority-medium
