Repository brandondombrowsky/BastCastle, pull requests merged in 2023-03, with the labels that each got.

#179 Cut links/added a few bullets to Wiki link section
  README.md
Labels: documentation, week9

#191 Google Integration
  .github/workflows/home-assistant.yml
  homeassistant-config/configuration.yaml
  homeassistant-config/dummy-certs/fullchain.pem
  homeassistant-config/dummy-certs/privkey.pem
  homeassistant-config/example_secrets.yaml
  homeassistant-config/google_assistant_integration.yaml
Labels: week9, priority-medium

#192 Restart HA after CD
  .github/workflows/deployment.yml
Labels: week9, priority-low

#195 Create a License
  LICENSE
Labels: week9, priority-medium

#197 Remove old stuff that clutters HA
  homeassistant-config/automations.yaml
  homeassistant-config/configuration.yaml
  homeassistant-config/scenes.yaml
  homeassistant-config/scripts.yaml
  homeassistant-config/scripts/loop_6_times.yaml
  homeassistant-config/scripts/scripts.yaml
Labels: priority-medium

#200 Fixed a few things/added Mac install link
  README.md
Labels: week9, priority-low

#199 Dependabot for Frenck's actions, Issue 187
  .github/dependabot.yml
Labels: week9, priority-low

#204 Display entities in Google App
  homeassistant-config/configuration.yaml
Labels: week10, priority-medium

#206 Change CI wording
  .github/workflows/configuration-check.yml
Labels: week10, priority-low

#210 Updated ReadMe
  README.md
Labels: week10, priority-high

#212 Issue #172 - Minor readme updates for dampers.
  README.md
Labels: documentation

#215 Issue #213 - Remove duplicate automations.
  homeassistant-config/automations.yaml
Labels: bug

#216 Add door lock script
  homeassistant-config/configuration.yaml
  homeassistant-config/example_secrets.yaml
  homeassistant-config/google_assistant_integration.yaml
  homeassistant-config/scripts.yaml
Labels: week10, priority-high

#218 Add readme image - router setup
  README.md
Labels: documentation, week10, priority-low

#221 Took out the `What?`s
  README.md
Labels: week10, priority-critical

#219 Add some links to ReadMe - wip
  README.md
Labels: documentation, week10

#223 add google integration link to readme
  README.md
Labels: documentation, week10, priority-low

#230 Add lock status icon to dashboard
  README.md
  homeassistant-config/automations.yaml
Labels: week11, priority-low

#231 Only run deployment on successful merge into main
  .github/workflows/deployment.yml
Labels: week11, priority-medium

#239 Issue #237 - Migrate damper check automation to prod HA
  homeassistant-config/automations.yaml
Labels: enhancement

#241 Nip and tuck of ReadMe
  README.md
Labels: week11

#243 Issue #242 - CD bug fix.
  .github/workflows/deployment.yml
Labels: bug, priority-critical

#245 remove check-door-status automation
  homeassistant-config/automations.yaml
Labels: week11, priority-high

#246 add lock demo script
  homeassistant-config/configuration.yaml
  homeassistant-config/scripts.yaml
Labels: week11, priority-high

#248 Issue #247 - Small updates to damper automations.
  homeassistant-config/automations.yaml
Labels: enhancement
